Add support for app-factory usage and test it.
not-kennethreitz/flask-sslify pull request #32
Opened 2015-04-24 10:25 UTC by tonyseek

@kennethreitz Please review. Thanks.

2016-01-30 02:15 UTC, kennethreitz commented
This looks like a nice set of changes. Will have to set some time aside to review.

2016-02-18 15:49 UTC, joshfriend commented on flask_sslify.py
> +        app.config.setdefault('SSLIFY_SUBDOMAINS', self.defaults['subdomains'])
@kennethreitz This PR will fix the regression introduced by #28 ([explanation](https://github.com/kennethreitz/flask-sslify/pull/28/files#r53332282))

2016-02-18 19:42 UTC, ryan-lane commented
This PR looks good to me. +1. Thank you for adding tests!

2016-02-18 21:37 UTC, kennethreitz commented
would you mind removing `tox.ini` and `setup.cfg`? I will be happy to merge then :)

2016-07-29 18:12 UTC, tonyseek commented
@kennethreitz I'm sorry for my late response.

I have removed the `tox.ini` and `setup.py`. Could you review it? Thanks!

2017-03-30 06:56 UTC, richmondwang approved these changes
this fixes the app factory pattern

2017-09-30 13:13 UTC, kennethreitz commented
merge conflict

2017-10-11 10:33 UTC, tonyseek commented
conflict resolved in a rebasing

2017-10-11 13:29 UTC, joshfriend requested changes

2017-10-11 13:29 UTC, joshfriend commented on flask_sslify.py
> +        app.config.setdefault('SSLIFY_AGE', self.defaults['AGE'])
None of the tests are running, this line is raising `KeyError: 'AGE'`. It should be `age` lowercase.

2017-10-11 13:29 UTC, joshfriend commented on tests/test_factory.py
> +    assert r.status_code == 301
The redirect tests do not pass, the app is returning 200

2017-10-11 13:29 UTC, joshfriend commented on tests/test_factory.py
> +class TestingContext(object):
I'd suggest calling this class `FixtureContext` or something else that doesn't begin with `Test`. py.test is trying to collect tests from it and is outputting a warning

2017-10-12 04:07 UTC, tonyseek commented
@joshfriend Sorry for that. I forgot to re-run testing before pushing. I fixed them all.

2017-10-12 12:28 UTC, joshfriend approved these changes

2018-06-14 02:07 UTC, rconradharris commented
This fix looks good, would be great to get this into PyPI at some point.

2019-02-16 06:14 UTC, merged